# Generated by Django 5.1.4 on 2025-02-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcodes',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
