# Generated by Django 5.1.4 on 2025-02-23 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_page', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
